/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Fieldore API
 * OpenAPI spec version: v1
 */
import axios from './axiosInstance';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface AddJobNoteRequest {
  /** @nullable */
  body?: string | null;
}

export interface AddJobPhotoRequest {
  /** @nullable */
  storagePath?: string | null;
  /** @nullable */
  caption?: string | null;
  /** @nullable */
  takenAt?: string | null;
}

export interface AddressDto {
  /** @nullable */
  line1?: string | null;
  /** @nullable */
  line2?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  stateOrProvince?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  country?: string | null;
}

export interface AuthResponse {
  /** @nullable */
  token?: string | null;
  expiresAtUtc?: string;
  userId?: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  businessId?: string | null;
}

export interface AuthResponseApiResponse {
  success?: boolean;
  statusCode?: number;
  /** @nullable */
  message?: string | null;
  data?: AuthResponse;
}

export interface BusinessDetailsResponse {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  tradeType?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  email?: string | null;
  address?: AddressDto;
  /** @nullable */
  timeZone?: string | null;
}

export interface BusinessDetailsResponseApiResponse {
  success?: boolean;
  statusCode?: number;
  /** @nullable */
  message?: string | null;
  data?: BusinessDetailsResponse;
}

export interface BusinessRegisterRequest {
  /** @nullable */
  businessName?: string | null;
  /** @nullable */
  tradeType?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  addressLine1?: string | null;
  /** @nullable */
  addressLine2?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  stateOrProvince?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  timeZone?: string | null;
}

export interface CountryLookupResponse {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  code?: string | null;
}

export interface CountryLookupResponseListApiResponse {
  success?: boolean;
  statusCode?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: CountryLookupResponse[] | null;
}

export interface CreateCustomerRequest {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  mobilePhone?: string | null;
  /** @nullable */
  alternatePhone?: string | null;
  /** @nullable */
  gateCode?: string | null;
  /** @nullable */
  petsNote?: string | null;
  /** @nullable */
  internalNotes?: string | null;
  billingSameAsService?: boolean;
  /** @nullable */
  addresses?: CustomerAddressRequest[] | null;
}

export interface CreateJobRequest {
  customerId?: string;
  /** @nullable */
  sourceLeadId?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  jobType?: string | null;
  /** @nullable */
  priority?: string | null;
  /** @nullable */
  status?: string | null;
  scheduledStartAt?: string;
  /** @nullable */
  scheduledEndAt?: string | null;
  /** @nullable */
  actualStartAt?: string | null;
  /** @nullable */
  actualEndAt?: string | null;
  /** @nullable */
  estimatedDurationMinutes?: number | null;
  useCustomerPrimaryAddress?: boolean;
  serviceAddress?: JobAddressRequest;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  assignments?: JobAssignmentRequest[] | null;
  /** @nullable */
  checklistItems?: JobChecklistItemRequest[] | null;
}

export interface CustomerAddressRequest {
  /** @nullable */
  label?: string | null;
  isPrimary?: boolean;
  isBilling?: boolean;
  /** @nullable */
  line1?: string | null;
  /** @nullable */
  line2?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  stateOrProvince?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  country?: string | null;
}

export interface CustomerAddressResponse {
  id?: string;
  /** @nullable */
  label?: string | null;
  isPrimary?: boolean;
  isBilling?: boolean;
  /** @nullable */
  line1?: string | null;
  /** @nullable */
  line2?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  stateOrProvince?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  country?: string | null;
}

export interface CustomerResponse {
  id?: string;
  businessId?: string;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  mobilePhone?: string | null;
  /** @nullable */
  alternatePhone?: string | null;
  /** @nullable */
  gateCode?: string | null;
  /** @nullable */
  petsNote?: string | null;
  /** @nullable */
  internalNotes?: string | null;
  billingSameAsService?: boolean;
  isActive?: boolean;
  /** @nullable */
  addresses?: CustomerAddressResponse[] | null;
  createdAt?: string;
  updatedAt?: string;
}

export interface CustomerResponseApiResponse {
  success?: boolean;
  statusCode?: number;
  /** @nullable */
  message?: string | null;
  data?: CustomerResponse;
}

export interface CustomerResponsePagedResponse {
  /** @nullable */
  data?: CustomerResponse[] | null;
  totalRecords?: number;
  pageNumber?: number;
  pageSize?: number;
}

export interface CustomerResponsePagedResponseApiResponse {
  success?: boolean;
  statusCode?: number;
  /** @nullable */
  message?: string | null;
  data?: CustomerResponsePagedResponse;
}

export interface DeleteCustomerResponse {
  customerId?: string;
  /** @nullable */
  message?: string | null;
}

export interface DeleteCustomerResponseApiResponse {
  success?: boolean;
  statusCode?: number;
  /** @nullable */
  message?: string | null;
  data?: DeleteCustomerResponse;
}

export interface DeleteJobResponse {
  jobId?: string;
  /** @nullable */
  message?: string | null;
}

export interface DeleteJobResponseApiResponse {
  success?: boolean;
  statusCode?: number;
  /** @nullable */
  message?: string | null;
  data?: DeleteJobResponse;
}

export interface ForgotPasswordRequest {
  /** @nullable */
  email?: string | null;
}

export interface ForgotPasswordResponse {
  /** @nullable */
  message?: string | null;
}

export interface ForgotPasswordResponseApiResponse {
  success?: boolean;
  statusCode?: number;
  /** @nullable */
  message?: string | null;
  data?: ForgotPasswordResponse;
}

export interface GetCustomersRequest {
  pageNumber?: number;
  pageSize?: number;
  /** @nullable */
  search?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  isActive?: boolean | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  state?: string | null;
}

export interface JobAddressRequest {
  /** @nullable */
  line1?: string | null;
  /** @nullable */
  line2?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  stateOrProvince?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
}

export interface JobAddressResponse {
  /** @nullable */
  line1?: string | null;
  /** @nullable */
  line2?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  stateOrProvince?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
}

export interface JobAssignmentRequest {
  userProfileId?: string;
  isPrimary?: boolean;
}

export interface JobAssignmentResponse {
  id?: string;
  userProfileId?: string;
  isPrimary?: boolean;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  email?: string | null;
}

export interface JobChecklistItemRequest {
  sortOrder?: number;
  /** @nullable */
  taskName?: string | null;
  isCompleted?: boolean;
}

export interface JobChecklistItemResponse {
  id?: string;
  sortOrder?: number;
  /** @nullable */
  taskName?: string | null;
  isCompleted?: boolean;
  /** @nullable */
  completedAt?: string | null;
  /** @nullable */
  completedByUserId?: string | null;
}

export interface JobCustomerSummaryResponse {
  id?: string;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  mobilePhone?: string | null;
  /** @nullable */
  email?: string | null;
}

export interface JobNoteResponse {
  id?: string;
  /** @nullable */
  createdByUserId?: string | null;
  /** @nullable */
  body?: string | null;
  createdAt?: string;
  /** @nullable */
  createdByDisplayName?: string | null;
}

export interface JobNoteResponseApiResponse {
  success?: boolean;
  statusCode?: number;
  /** @nullable */
  message?: string | null;
  data?: JobNoteResponse;
}

export interface JobPhotoResponse {
  id?: string;
  /** @nullable */
  uploadedByUserId?: string | null;
  /** @nullable */
  storagePath?: string | null;
  /** @nullable */
  caption?: string | null;
  /** @nullable */
  takenAt?: string | null;
  createdAt?: string;
}

export interface JobPhotoResponseApiResponse {
  success?: boolean;
  statusCode?: number;
  /** @nullable */
  message?: string | null;
  data?: JobPhotoResponse;
}

export interface JobResponse {
  id?: string;
  businessId?: string;
  customerId?: string;
  /** @nullable */
  sourceLeadId?: string | null;
  /** @nullable */
  jobNumber?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  jobType?: string | null;
  /** @nullable */
  priority?: string | null;
  /** @nullable */
  status?: string | null;
  scheduledStartAt?: string;
  /** @nullable */
  scheduledEndAt?: string | null;
  /** @nullable */
  actualStartAt?: string | null;
  /** @nullable */
  actualEndAt?: string | null;
  /** @nullable */
  estimatedDurationMinutes?: number | null;
  useCustomerPrimaryAddress?: boolean;
  serviceAddress?: JobAddressResponse;
  /** @nullable */
  description?: string | null;
  customer?: JobCustomerSummaryResponse;
  /** @nullable */
  assignments?: JobAssignmentResponse[] | null;
  /** @nullable */
  checklistItems?: JobChecklistItemResponse[] | null;
  /** @nullable */
  notes?: JobNoteResponse[] | null;
  /** @nullable */
  photos?: JobPhotoResponse[] | null;
  createdAt?: string;
  updatedAt?: string;
}

export interface JobResponseApiResponse {
  success?: boolean;
  statusCode?: number;
  /** @nullable */
  message?: string | null;
  data?: JobResponse;
}

export interface JobResponsePagedResponse {
  /** @nullable */
  data?: JobResponse[] | null;
  totalRecords?: number;
  pageNumber?: number;
  pageSize?: number;
}

export interface JobResponsePagedResponseApiResponse {
  success?: boolean;
  statusCode?: number;
  /** @nullable */
  message?: string | null;
  data?: JobResponsePagedResponse;
}

export interface LoginRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}

export interface ReplaceJobAssignmentsRequest {
  /** @nullable */
  assignments?: JobAssignmentRequest[] | null;
}

export interface ReplaceJobChecklistRequest {
  /** @nullable */
  checklistItems?: JobChecklistItemRequest[] | null;
}

export interface SignupRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
}

export interface StateProvinceLookupResponse {
  id?: string;
  countryId?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  code?: string | null;
}

export interface StateProvinceLookupResponseListApiResponse {
  success?: boolean;
  statusCode?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: StateProvinceLookupResponse[] | null;
}

export interface UpdateCustomerRequest {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  mobilePhone?: string | null;
  /** @nullable */
  alternatePhone?: string | null;
  /** @nullable */
  gateCode?: string | null;
  /** @nullable */
  petsNote?: string | null;
  /** @nullable */
  internalNotes?: string | null;
  billingSameAsService?: boolean;
  /** @nullable */
  addresses?: CustomerAddressRequest[] | null;
}

export interface UpdateJobRequest {
  customerId?: string;
  /** @nullable */
  sourceLeadId?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  jobType?: string | null;
  /** @nullable */
  priority?: string | null;
  /** @nullable */
  status?: string | null;
  scheduledStartAt?: string;
  /** @nullable */
  scheduledEndAt?: string | null;
  /** @nullable */
  actualStartAt?: string | null;
  /** @nullable */
  actualEndAt?: string | null;
  /** @nullable */
  estimatedDurationMinutes?: number | null;
  useCustomerPrimaryAddress?: boolean;
  serviceAddress?: JobAddressRequest;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  assignments?: JobAssignmentRequest[] | null;
  /** @nullable */
  checklistItems?: JobChecklistItemRequest[] | null;
}

export interface UpdateJobStatusRequest {
  /** @nullable */
  status?: string | null;
  /** @nullable */
  actualStartAt?: string | null;
  /** @nullable */
  actualEndAt?: string | null;
}

export type PostApiJobsGetAllJobsParams = {
PageNumber?: number;
PageSize?: number;
Search?: string;
CustomerId?: string;
Status?: string;
Priority?: string;
AssignedUserProfileId?: string;
ScheduledFrom?: string;
ScheduledTo?: string;
};

export type GetApiLocationsStatesParams = {
countryId?: string;
countryCode?: string;
};

export const getFieldoreAPI = () => {
const postApiAuthLogin = <TData = AxiosResponse<AuthResponseApiResponse>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/Auth/login`,
      loginRequest,options
    );
  }

const postApiAuthSignup = <TData = AxiosResponse<AuthResponseApiResponse>>(
    signupRequest: SignupRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/Auth/signup`,
      signupRequest,options
    );
  }

const postApiAuthBusinessRegister = <TData = AxiosResponse<AuthResponseApiResponse>>(
    businessRegisterRequest: BusinessRegisterRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/Auth/business-register`,
      businessRegisterRequest,options
    );
  }

const getApiAuthGetBusinessDetails = <TData = AxiosResponse<BusinessDetailsResponseApiResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Auth/get-business-details`,options
    );
  }

const postApiAuthForgotPassword = <TData = AxiosResponse<ForgotPasswordResponseApiResponse>>(
    forgotPasswordRequest: ForgotPasswordRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/Auth/forgot-password`,
      forgotPasswordRequest,options
    );
  }

const postApiCustomersCreateCustomer = <TData = AxiosResponse<CustomerResponseApiResponse>>(
    createCustomerRequest: CreateCustomerRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/Customers/create-customer`,
      createCustomerRequest,options
    );
  }

const postApiCustomersGetAllCustomers = <TData = AxiosResponse<CustomerResponsePagedResponseApiResponse>>(
    getCustomersRequest: GetCustomersRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/Customers/getAll-customers`,
      getCustomersRequest,options
    );
  }

const getApiCustomersGetByIdCustomerId = <TData = AxiosResponse<CustomerResponseApiResponse>>(
    customerId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Customers/getById/${customerId}`,options
    );
  }

const putApiCustomersUpdateCustomerCustomerId = <TData = AxiosResponse<CustomerResponseApiResponse>>(
    customerId: string,
    updateCustomerRequest: UpdateCustomerRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/Customers/update-customer/${customerId}`,
      updateCustomerRequest,options
    );
  }

const deleteApiCustomersDeleteCustomerCustomerId = <TData = AxiosResponse<DeleteCustomerResponseApiResponse>>(
    customerId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/Customers/delete-customer/${customerId}`,options
    );
  }

const getHealthDb = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/health/db`,options
    );
  }

const postApiJobsCreateJob = <TData = AxiosResponse<JobResponseApiResponse>>(
    createJobRequest: CreateJobRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/Jobs/create-job`,
      createJobRequest,options
    );
  }

const postApiJobsGetAllJobs = <TData = AxiosResponse<JobResponsePagedResponseApiResponse>>(
    params?: PostApiJobsGetAllJobsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/Jobs/getAll-jobs`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getApiJobsGetByIdJobId = <TData = AxiosResponse<JobResponseApiResponse>>(
    jobId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Jobs/getById/${jobId}`,options
    );
  }

const putApiJobsUpdateJobJobId = <TData = AxiosResponse<JobResponseApiResponse>>(
    jobId: string,
    updateJobRequest: UpdateJobRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/Jobs/update-job/${jobId}`,
      updateJobRequest,options
    );
  }

const deleteApiJobsDeleteJobJobId = <TData = AxiosResponse<DeleteJobResponseApiResponse>>(
    jobId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/Jobs/delete-job/${jobId}`,options
    );
  }

const patchApiJobsUpdateStatusJobId = <TData = AxiosResponse<JobResponseApiResponse>>(
    jobId: string,
    updateJobStatusRequest: UpdateJobStatusRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/Jobs/update-status/${jobId}`,
      updateJobStatusRequest,options
    );
  }

const putApiJobsReplaceAssignmentsJobId = <TData = AxiosResponse<JobResponseApiResponse>>(
    jobId: string,
    replaceJobAssignmentsRequest: ReplaceJobAssignmentsRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/Jobs/replace-assignments/${jobId}`,
      replaceJobAssignmentsRequest,options
    );
  }

const putApiJobsReplaceChecklistJobId = <TData = AxiosResponse<JobResponseApiResponse>>(
    jobId: string,
    replaceJobChecklistRequest: ReplaceJobChecklistRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/Jobs/replace-checklist/${jobId}`,
      replaceJobChecklistRequest,options
    );
  }

const postApiJobsAddNoteJobId = <TData = AxiosResponse<JobNoteResponseApiResponse>>(
    jobId: string,
    addJobNoteRequest: AddJobNoteRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/Jobs/add-note/${jobId}`,
      addJobNoteRequest,options
    );
  }

const postApiJobsAddPhotoJobId = <TData = AxiosResponse<JobPhotoResponseApiResponse>>(
    jobId: string,
    addJobPhotoRequest: AddJobPhotoRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/Jobs/add-photo/${jobId}`,
      addJobPhotoRequest,options
    );
  }

const getApiLocationsCountries = <TData = AxiosResponse<CountryLookupResponseListApiResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Locations/countries`,options
    );
  }

const getApiLocationsStates = <TData = AxiosResponse<StateProvinceLookupResponseListApiResponse>>(
    params?: GetApiLocationsStatesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Locations/states`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

return {postApiAuthLogin,postApiAuthSignup,postApiAuthBusinessRegister,getApiAuthGetBusinessDetails,postApiAuthForgotPassword,postApiCustomersCreateCustomer,postApiCustomersGetAllCustomers,getApiCustomersGetByIdCustomerId,putApiCustomersUpdateCustomerCustomerId,deleteApiCustomersDeleteCustomerCustomerId,getHealthDb,postApiJobsCreateJob,postApiJobsGetAllJobs,getApiJobsGetByIdJobId,putApiJobsUpdateJobJobId,deleteApiJobsDeleteJobJobId,patchApiJobsUpdateStatusJobId,putApiJobsReplaceAssignmentsJobId,putApiJobsReplaceChecklistJobId,postApiJobsAddNoteJobId,postApiJobsAddPhotoJobId,getApiLocationsCountries,getApiLocationsStates}};
export type PostApiAuthLoginResult = AxiosResponse<AuthResponseApiResponse>
export type PostApiAuthSignupResult = AxiosResponse<AuthResponseApiResponse>
export type PostApiAuthBusinessRegisterResult = AxiosResponse<AuthResponseApiResponse>
export type GetApiAuthGetBusinessDetailsResult = AxiosResponse<BusinessDetailsResponseApiResponse>
export type PostApiAuthForgotPasswordResult = AxiosResponse<ForgotPasswordResponseApiResponse>
export type PostApiCustomersCreateCustomerResult = AxiosResponse<CustomerResponseApiResponse>
export type PostApiCustomersGetAllCustomersResult = AxiosResponse<CustomerResponsePagedResponseApiResponse>
export type GetApiCustomersGetByIdCustomerIdResult = AxiosResponse<CustomerResponseApiResponse>
export type PutApiCustomersUpdateCustomerCustomerIdResult = AxiosResponse<CustomerResponseApiResponse>
export type DeleteApiCustomersDeleteCustomerCustomerIdResult = AxiosResponse<DeleteCustomerResponseApiResponse>
export type GetHealthDbResult = AxiosResponse<void>
export type PostApiJobsCreateJobResult = AxiosResponse<JobResponseApiResponse>
export type PostApiJobsGetAllJobsResult = AxiosResponse<JobResponsePagedResponseApiResponse>
export type GetApiJobsGetByIdJobIdResult = AxiosResponse<JobResponseApiResponse>
export type PutApiJobsUpdateJobJobIdResult = AxiosResponse<JobResponseApiResponse>
export type DeleteApiJobsDeleteJobJobIdResult = AxiosResponse<DeleteJobResponseApiResponse>
export type PatchApiJobsUpdateStatusJobIdResult = AxiosResponse<JobResponseApiResponse>
export type PutApiJobsReplaceAssignmentsJobIdResult = AxiosResponse<JobResponseApiResponse>
export type PutApiJobsReplaceChecklistJobIdResult = AxiosResponse<JobResponseApiResponse>
export type PostApiJobsAddNoteJobIdResult = AxiosResponse<JobNoteResponseApiResponse>
export type PostApiJobsAddPhotoJobIdResult = AxiosResponse<JobPhotoResponseApiResponse>
export type GetApiLocationsCountriesResult = AxiosResponse<CountryLookupResponseListApiResponse>
export type GetApiLocationsStatesResult = AxiosResponse<StateProvinceLookupResponseListApiResponse>
